### ISSUE TITLE
can.socketcan.native -ERROR - [Errno 100] network is down

### ISSUE THREAD

**Issue by avelampudi** [linux-can/can-utils#32]
This is a very odd problem that I'm having.

`2016-10-27 14:23:29,488 - can.socketcan.native - INFO - Created a socket
2016-10-27 14:23:29,492 - can.socketcan.native - DEBUG - Binding socket to chann                                                                                                             el=can1
2016-10-27 14:23:29,495 - can.socketcan.native - DEBUG - Bound socket.
2016-10-27 14:23:29,498 - Receiver - DEBUG - can0
2016-10-27 14:23:29,502 - can.socketcan.native - INFO - Created a socket
2016-10-27 14:23:29,505 - can.socketcan.native - DEBUG - Binding socket to chann                                                                                                             el=can0
2016-10-27 14:23:29,508 - can.socketcan.native - DEBUG - Bound socket.
2016-10-27 14:23:29,513 - can.socketcan.native - ERROR - [Errno 100] Network is                                                                                                              down
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/v7/v7.2/can/notifier.py", line 34, in rx_thread
    msg = self.bus.recv(self.timeout)
  File "/home/v7/v7.2/can/interfaces/socketcan_native.py", line 309, in recv
    packet = capturePacket(self.socket)
  File "/home/v7/v7.2/can/interfaces/socketcan_native.py", line 242, in captureP                                                                                                             acket
    can_id, can_dlc, data = dissect_can_frame(cf)
UnboundLocalError: local variable 'cf' referenced before assignment
`

I'm running this on a beaglebone - Debian, kernel: 4.1.15  with the TT3201-001-05 CAN cape.
Everything worked perfectly fine earlier, but  this is the second time my beaglebone has had this problem (last time to solve the 'network is down' issue, I switched beaglebones)

**Comment by hartkopp** [comment]
This is a Python or Beaglebone issue and has nothing to do with can-utils.
You may ask for help on the Linux-CAN mailing list: linux-can@vger.kernel.org
http://vger.kernel.org/vger-lists.html#linux-can
