### ISSUE TITLE
Candump - AddressSanitizer: stack-use-after-scope

### ISSUE THREAD

**Issue by HBLocker** [linux-can/can-utils#379]
I got this issue when I compiled with ASAN and then tired to use candump -l any
To recreate the issue: 
``` bash

./configure CFLAGS="-fsanitize=address -g" CXXFLAGS="-fsanitize=address -g" LDFLAGS="-fsanitize=address" 
make 
./ candump -l any
```

Output is as follows
```sh

=================================================================
==323765==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffe49e20cc0 at pc 0x7fe1e1e42dcb bp 0x7ffe49e203c0 sp 0x7ffe49e1fb38
READ of size 30 at 0x7ffe49e20cc0 thread T0
    #0 0x7fe1e1e42dca in printf_common ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:546
    #1 0x7fe1e1e43fb6 in __interceptor_vfprintf ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1604
    #2 0x7fe1e1e441ce in __interceptor___fprintf_chk ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1666
    #3 0x55f3ec80f64a in fprintf /usr/include/x86_64-linux-gnu/bits/stdio2.h:100
    #4 0x55f3ec80f64a in main /home/harry/can/can-utils/candump.c:695
    #5 0x7fe1e1bd8082 in __libc_start_main ../csu/libc-start.c:308
    #6 0x55f3ec81090d in _start (/usr/local/bin/candump+0xa90d)

Address 0x7ffe49e20cc0 is located in stack of thread T0 at offset 1696 in frame
    #0 0x55f3ec80c8cf in main /home/harry/can/can-utils/candump.c:281

  This frame has 31 object(s):
    [48, 52) 'rcvbuf_size' (line 300)
    [64, 68) 'join_filter' (line 303)
    [80, 84) 'err_mask' (line 313)
    [96, 100) 'curr_rcvbuf_size' (line 601)
    [112, 116) 'curr_rcvbuf_size_len' (line 602)
    [128, 132) 'timestamping_flags' (line 632)
    [144, 148) 'timestamp_on' (line 642)
    [160, 164) 'dropmonitor_on' (line 653)
    [176, 184) 'currtime' (line 670)
    [208, 220) 'event_setup' (line 284)
    [240, 256) 'iov' (line 309)
    [272, 288) 'tv' (line 317)
    [304, 320) 'last_tv' (line 317)
    [336, 360) 'addr' (line 305)
    [400, 456) 'msg' (line 310)
    [496, 552) 'now' (line 671)
    [592, 648) 'tm' (line 237)
    [688, 744) 'tm' (line 237)
    [784, 840) 'tm' (line 237)
    [880, 920) 'ifr' (line 316)
    [960, 1000) 'ifr' (line 180)
    [1040, 1112) 'frame' (line 314)
    [1152, 1344) 'events_pending' (line 283)
    [1408, 1433) 'timestring' (line 238)
    [1472, 1497) 'timestring' (line 238)
    [1536, 1561) 'timestring' (line 238)
    [1600, 1650) 'ts_buf' (line 811)
    [1696, 1779) 'fname' (line 672) <== Memory access at offset 1696 is inside this variable
    [1824, 1944) 'ctrlmsg' (line 306)
    [1984, 2264) 'buf' (line 810)
    [2336, 2616) 'buf' (line 823)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:546 in printf_common
Shadow bytes around the buggy address:
  0x1000493bc140: 00 f2 f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 f2
  0x1000493bc150: f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000493bc160: 00 00 00 00 00 00 00 00 00 00 00 00 f2 f2 f2 f2
  0x1000493bc170: f2 f2 f2 f2 00 00 00 01 f2 f2 f2 f2 00 00 00 01
  0x1000493bc180: f2 f2 f2 f2 00 00 00 01 f2 f2 f2 f2 00 00 00 00
=>0x1000493bc190: 00 00 02 f2 f2 f2 f2 f2[f8]f8 f8 f8 f8 f8 f8 f8
  0x1000493bc1a0: f8 f8 f8 f2 f2 f2 f2 f2 00 00 00 00 00 00 00 00
  0x1000493bc1b0: 00 00 00 00 00 00 00 f2 f2 f2 f2 f2 00 00 00 00
  0x1000493bc1c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000493bc1d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f2
  0x1000493bc1e0: f2 f2 f2 f2 f2 f2 f2 f2 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==323765==ABORTING
```

**Comment by marckleinebudde** [comment]
Thanks for reporting the problem!
